[package]
name = "avila-coordinator"
version = "0.1.0"
edition = "2021"
authors = ["Nícolas Ávila <nicolas@avila.inc>"]
license = "MIT OR Apache-2.0"
description = "Task coordination"

[dependencies]
avila-error = { version = "0.2.0", path = "../avila-error" }
